# Generated by Django 5.0.7 on 2025-03-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Support staff notes', null=True),
        ),
    ]
